version: '3'
services:
  dind:
    image: docker:dind
    privileged: true
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

  jenkins:
    image: jenkins/jenkins:lts
    environment:
      - DOCKER_HOST=tcp://dind:2375
    ports:
      - 8080:8080
    volumes:
      - jenkins_home:/var/jenkins_home
    depends_on:
      - dind

volumes:
  jenkins_home:
